modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="vehicle"
version="0.43.5"
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/vehicle/update.json"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle.png"
credits="Phylogeny https://github.com/Phylogeny"
authors="MrCrayfish"
description="A mod that adds vehicles into Minecraft!"

[[dependencies.vehicle]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.3.3,)"
    ordering="AFTER"
    side="BOTH"